spring.application.name=LostAndFound

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://thomas.proxy.rlwy.net:36382/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:xgYiqMHiGHBwHaXqmjOPygePdcBuEAoG}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Your custom AI properties
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent
gemini.api.key=${GEMINI_API_KEY:AIzaSyAbdQCfOYcwtpKsxg0pq7I2FqeBblXQjwY}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dssbsnk9c}
cloudinary.api-key=${CLOUDINARY_API_KEY:142734952894217}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:yqIw74yjDZFqA4f5A3eMTgtSavI}

# Configure multipart file upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JWT Configuration
spring.app.jwtSecret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
spring.app.jwtExpirationMS=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:88sheoran@gmail.com}
spring.mail.password=${MAIL_PASSWORD:wfyh agdk fcti kpyt}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay Configuration (TEST MODE)
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_T0DWiNlkJJrMYm}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:a7ibUPNR73fC2rVm6TNAcKDS}