package com.sheoran.LostAndFound.service.services;


import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.Map;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class ImageUploadService {

    private final Cloudinary cloudinary;

    public String uploadImage(MultipartFile file) throws IOException {
        // Generate a unique filename to prevent overwriting
        String publicId = UUID.randomUUID().toString();

        Map uploadResult = cloudinary.uploader().upload(file.getBytes(),
                ObjectUtils.asMap(
                        "public_id", "campus_hub/" + publicId, // Creates a folder in your Cloudinary
                        "resource_type", "image"
                ));

        // Return the secure HTTPS URL generated by Cloudinary
        return uploadResult.get("secure_url").toString();
    }
}